# config/vanderpol_config.yaml
# Van der Pol Oscillator Configuration
# System: dx1/dt = x2
#         dx2/dt = μ(1 - x1²)x2 - x1

system:
  name: "Nonlinear Schrodinger Equation 4D"
  description: "Nonlinear Schrodinger equation in 4D with quadratic nonlinearity"
  n_states: 4
  truncation_order: 4
  
# System matrices
matrices:
  # Linear part:-iH1 * x
  A1: [ [ 0.,  0., -0.,  8.],
        [ 0.,  0., -8. ,-0.],
        [ 0.,  8.,  0.,  0.],
        [-8.,  0.,  0.,  0.] ]  # Antihermitian matrix for 2D Schrodinger equation
         # Antihermitian matrix for 2D Schrodinger equation
  
  # Quadratic part: A2 * (x ⊗ x)
  # For Van der Pol: dx2/dt includes -μ*x1²*x2 term
  # Kronecker product ordering: [x1*x1, x1*x2, x2*x1, x2*x2]
  A2: [  [0.9, 6, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.] ]


# Initial conditions
initial_conditions:
  x0: [1.0, 0.0 , 0.0, 0.0]
  description: "Initial condition for the nonlinear Schrodinger equation in 4D"

# Simulation parameters  
simulation:
  t_start: 0.0
  t_end: 100.0
  n_points: 400
  solver_method: 'Radau'
  rtol: 1.0e-10
  atol: 1.0e-12

# System-specific parameters
parameters:
  mu: 1.0  # Schrodinger Equation parameter

# Expected behavior
expected_behavior:
  type: "limit_cycle"
  description: "Unknown behavior for the nonlinear Schrodinger equation in 4D"
  characteristic_time: 10.0

# Plotting parameters
plotting:
  figure_size: [12, 8]
  dpi: 300
  save_format: 'png'
  save_plots: true
  output_directory: 'results/schrodinger_4d/'
  show_plots: false
  phase_plot: true  # Enable phase portrait plotting

# Logging
logging:
  level: 'INFO'
  log_to_file: true
  log_file: 'logs/schrodinger_4d.log'

# Performance
performance:
  use_parallel: false
  n_workers: 4
  memory_limit_gb: 8